version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
      AUTH_URL: ${AUTH_URL}
      ATTENDANCE_URL: ${ATTENDANCE_URL}
      LIB_URL: ${LIB_URL}
