version: "3.8"

services:
  app:
    container_name: attendance-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres-db:5432/attendance
    networks:
      - internal-network

networks:
  internal-network: # Define the "internal" network
    name: internal-network
    driver: bridge # You can specify the driver as needed
